import Head from "next/head"
import Script from "next/script"
export const metadata = {
  title: 'hello',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
   <head>
  <Script 
  async 
  src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6845208892302274"
     crossorigin="anonymous`}
     strategy="afterInteractive"
      />
   </head>
      <body>{children}</body>
    </html>
  )
}
