import Head from "next/head"

export const metadata = {
  title: 'hello',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
   <head>
   <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6845208892302274"
     ></script>
   </head>
      <body>{children}</body>
    </html>
  )
}
