export default[
{
    title:"Who won yesterday ipl match held between RR vs DC",
    id:1,
    img:"hello.jpg",
    desc:"The yesterday match was between rajasthan royals and Delhi capitals was massive.Rajsthan royals ",
    content:`The yesterday match was between rajasthan royals and Delhi capitals was massive.Rajsthan royals they have won one match before if they won this match they will reach at second position of points table below Chennai super kings.For Delhi capitals they have to win this match in order to make one points for their  because they have loose one match before this  if they loose this match will be at third last position of points table.The match started with and Delhi capitals won the toss and they opted to ball first after that openers of rajsthanroyals came at the field.The openers from Rajasthan royals teams were Jos butlerwho is an England players and Yashasvi jaiswal who is an Indian player.In starting they both played well but after that RR lost their first wicket in the form of yashasvi jaiswal.Yashasvi
 jaiswal got out at 5 runs at 7 ball in the balling of Mukesh Kumar.Aftee that Sanju Samson came on the cries who is the captain of rajsthan royals after that RR lost their second wicket of Jos butler who is the another opener of rajsthan royals.Jos butler got out at 11 runs in 16 balls in the balling kuldeep yadav with lbw After that Sanju Samson also got out at 15 runs in 14 balls .Then riyan parag came for batting and he played very well for the rajsthan royals he scored 84 runs at 45 balls with 7 fours and 6 sixes at was the massive batting of riyan parag.After the 20 overs of batting the rajsthan royals scored 185 on score board.After that in second innings Delhi capitals came for batting for winning they may have to score 173 runs at 120 balls.The openers of Delhi capitals were David Warner and Mitchell marsh.In the starting Delhi capitals scored nice runs.But after that Delhi loose there first wicket in the form of Mitchell Marsh.He scored just 23 runs at 12 balls with 5 fours it was the nice batting of Mitchell marsh but in the balling of nandre burger he got out After that Rickey bhui came for batting and he also got out at 0 runs with 2 balls.After that rishab pant came for batting and  he was the captain of the Delhi capitals and he played well in this match but after some help also got out.He scored 28 runs at 26 balls.Now the match whole match was on the shoulder of David Warner but he also got out.Tristan Stubbs of Delhi capitals gave is 100% for making Delhi capitals to win this match but due to the best ballers of rajsthan it was not possible and due to this Delhi capitals lost there 2 match in front of RR.RR reach at second position in the points table with the office 4 Which teams match is going to held tomorrow? Tommorrow on 29th March the match is going to held between Royal challengers banglore and Kolkata knight riders.Both the teams have won one one matches.It will toughest match of tata ipl .`
},
{
    title:"Who won the match held between CSK and GT",
    id:2,
    img:"by.jpg",
    desc:"Today on 26th of March 2024 the match was between two teams Chennai super kings and Gujrat titans.",
    content:`Today on 26th of March 2024 the match was between two teams Chennai super kings and Gujrat titans.This both the teams were the finalists of last season of tata ipl 2023.And last year CSK won that final match against gujrat titans and it was the wonderful match.In today's match gujrat titans was having a chance to win the match against CSK and took the revenge.The toss was wonderful by gujrat titans and they opted to ball first they gave chance to CSK for batting.Ruturaj gaikwad and Ravindra were the opener for the CSK and they started the match with well partnership.Ravindra was on the fire after the match started he scored 46 runs at 20 balls and after that he got out in the balling of Rashid Khan and keeping by shah.If he would have not out with stumping he would have scored century because his performance was well from the starting.After the wicket of ravindra ruturaj started to hot boundaries he also scored 46 runs.It was the nice batting of ruturaj after that he got out.Shivam Dube from Chennai super kings teams scored 50 runs for CSK.Due to the such type of gameplay of CSK they scored 207 runs in 20 overs.
In the next innings of the match gujrat titans came for batting in the starting they started to hit boundaries.Shubhnam gill and Shah were the openers from the gujrat titans teams.Shubnam gill is the captain of gujrat titans and Ruturaj gaikwad is the captain of the CSK team.After some boundaries in 1 and 2nd over CSK got the wicket of the captain of gujrat titans means shubnam gill.After this wicket all the batsman where not able to play well but tried there best for scored the runs but the runs were lot.After sai Sudarshan came here also hit some boundaries and Miller also hit some boundaries but after that they get out.And then Rahul tevatiya and Rashid came they also not did anything for there team Rashid Khan just scored  runs at 2 balls.After there wicket Umesh Yadav came for batting and he also scored some runs but it was not that match runs to win the match.At last CSK won the match with 63 runs.Afyer winning this match CSK reach at the top of the points table after winning the two matches continuously one match in front of RCB and another in front of Gujrat titans they both are the toughest teams of tata ipl but CSK has shown why they are the champion.
Upcoming matches of tata ipl 2024 ?
Upcoming matches of tata ipl is going to held between sunrisers Hyderabad and Mumbai Indians.Patcumming is the captain of sunrisers Hyderabad and Hardhik pandya is the captain of Mumbai Indians.`
    
},
{
    title:"Who won the tata ipl match between Mumbai Indians and hydrabad",
    id:3,
    img:"hi.jpg",
    desc:"Yesterday there was a match between two best teams of tata ipl.Mumbai Indians vs Sunrisers Hyderabad ",
    content:`Yesterday there was a match between two best teams of tata ipl.Mumbai Indians vs Sunrisers Hyderabad.Mumbai Indian have won 5 trophy of ipl and Hyderabad had won 1 trophy of ipl so due this week can say that both the teams are best in tata ipl.The match started with the toss and toss was wonderful by Mumbai Indians and they opted to ball first after that  openers of sunrisers Hyderabad came for batting from starting onwards they started to hit boundaries in the game.Mumbai Indians gave the chance for a young for balling but this was there biggest mistake because he gave more runs in this match his name was mafaka and he is and South African player he gave 66 runs at four over.Travis head played very well in this match and he scored half century in this match.He scored 62 runs at 24 ball with 9 fours and 3 sixes.In this match mayank agrawal tried to hit some boundaries but it was not possible from him and he got out just scoring 11 runs at 13 balls.After that abhisek warma came for batting he also played very well in this match he scored 62 runs at 24 balls.He also completed his half century in this match.And after the wicket of traves head markram came for batting and he also played and after Abhishek warma got out and after this klaaseen came for batting at peach.And after he arrived at ground he just started to smashed the boundary against Mumbai Indians.Klaaseen is the wicket keeper of sunrisers Hyderabad and in last match he scored well for sunrisers Hyderabad against kkr but they were not able win that match.But in this match due to well gameplay of Hyderabad players they scored 277 runs at 3 wicket in 20 overs and this was highest score in the ipl history earlier it was the record of RCB of 263 runs at 20 overs but in today's match it got broke up.After that in second innings Mumbai Indians came for batting in starting Rohit and ishan kishan started to smashed some boundaries but after that Mumbai Indian lose their first wicket of ishan kishan.And after few overs they lost their second wicket in the form of Rohit Sharma.Munbai Indians tried very much chased the runs but they were not able to that because Hyderabad ballers played well but than also Mumbai Indians players scored 246 runs at 5 wicket.At last sunrisers Hyderabad won there first match of ipl 2024.And Mumbai Indians has lost its second match of ipl.It was the wonderful match because in this match previous records of ipl got broken.`

}





]