export default[
{
    title:"Who won yesterday ipl match held between RR vs DC",
    id:1,
    img:"hello.jpg",
    desc:"The yesterday match was between rajasthan royals and Delhi capitals was massive.Rajsthan royals ",
    content:`The yesterday match was between rajasthan royals and Delhi capitals was massive.Rajsthan royals they have won one match before if they won this match they will reach at second position of points table below Chennai super kings.For Delhi capitals they have to win this match in order to make one points for their  because they have loose one match before this  if they loose this match will be at third last position of points table.The match started with and Delhi capitals won the toss and they opted to ball first after that openers of rajsthanroyals came at the field.The openers from Rajasthan royals teams were Jos butlerwho is an England players and Yashasvi jaiswal who is an Indian player.In starting they both played well but after that RR lost their first wicket in the form of yashasvi jaiswal.Yashasvi
 jaiswal got out at 5 runs at 7 ball in the balling of Mukesh Kumar.Aftee that Sanju Samson came on the cries who is the captain of rajsthan royals after that RR lost their second wicket of Jos butler who is the another opener of rajsthan royals.Jos butler got out at 11 runs in 16 balls in the balling kuldeep yadav with lbw After that Sanju Samson also got out at 15 runs in 14 balls .Then riyan parag came for batting and he played very well for the rajsthan royals he scored 84 runs at 45 balls with 7 fours and 6 sixes at was the massive batting of riyan parag.After the 20 overs of batting the rajsthan royals scored 185 on score board.After that in second innings Delhi capitals came for batting for winning they may have to score 173 runs at 120 balls.The openers of Delhi capitals were David Warner and Mitchell marsh.In the starting Delhi capitals scored nice runs.But after that Delhi loose there first wicket in the form of Mitchell Marsh.He scored just 23 runs at 12 balls with 5 fours it was the nice batting of Mitchell marsh but in the balling of nandre burger he got out After that Rickey bhui came for batting and he also got out at 0 runs with 2 balls.After that rishab pant came for batting and  he was the captain of the Delhi capitals and he played well in this match but after some help also got out.He scored 28 runs at 26 balls.Now the match whole match was on the shoulder of David Warner but he also got out.Tristan Stubbs of Delhi capitals gave is 100% for making Delhi capitals to win this match but due to the best ballers of rajsthan it was not possible and due to this Delhi capitals lost there 2 match in front of RR.RR reach at second position in the points table with the office 4 Which teams match is going to held tomorrow? Tommorrow on 29th March the match is going to held between Royal challengers banglore and Kolkata knight riders.Both the teams have won one one matches.It will toughest match of tata ipl .`
},
{
    title:"Who won the match held between CSK and GT",
    id:2,
    img:"by.jpg",
    desc:"Today on 26th of March 2024 the match was between two teams Chennai super kings and Gujrat titans.",
    content:`Today on 26th of March 2024 the match was between two teams Chennai super kings and Gujrat titans.This both the teams were the finalists of last season of tata ipl 2023.And last year CSK won that final match against gujrat titans and it was the wonderful match.In today's match gujrat titans was having a chance to win the match against CSK and took the revenge.The toss was wonderful by gujrat titans and they opted to ball first they gave chance to CSK for batting.Ruturaj gaikwad and Ravindra were the opener for the CSK and they started the match with well partnership.Ravindra was on the fire after the match started he scored 46 runs at 20 balls and after that he got out in the balling of Rashid Khan and keeping by shah.If he would have not out with stumping he would have scored century because his performance was well from the starting.After the wicket of ravindra ruturaj started to hot boundaries he also scored 46 runs.It was the nice batting of ruturaj after that he got out.Shivam Dube from Chennai super kings teams scored 50 runs for CSK.Due to the such type of gameplay of CSK they scored 207 runs in 20 overs.
In the next innings of the match gujrat titans came for batting in the starting they started to hit boundaries.Shubhnam gill and Shah were the openers from the gujrat titans teams.Shubnam gill is the captain of gujrat titans and Ruturaj gaikwad is the captain of the CSK team.After some boundaries in 1 and 2nd over CSK got the wicket of the captain of gujrat titans means shubnam gill.After this wicket all the batsman where not able to play well but tried there best for scored the runs but the runs were lot.After sai Sudarshan came here also hit some boundaries and Miller also hit some boundaries but after that they get out.And then Rahul tevatiya and Rashid came they also not did anything for there team Rashid Khan just scored  runs at 2 balls.After there wicket Umesh Yadav came for batting and he also scored some runs but it was not that match runs to win the match.At last CSK won the match with 63 runs.Afyer winning this match CSK reach at the top of the points table after winning the two matches continuously one match in front of RCB and another in front of Gujrat titans they both are the toughest teams of tata ipl but CSK has shown why they are the champion.
Upcoming matches of tata ipl 2024 ?
Upcoming matches of tata ipl is going to held between sunrisers Hyderabad and Mumbai Indians.Patcumming is the captain of sunrisers Hyderabad and Hardhik pandya is the captain of Mumbai Indians.`
    
},
{
    title:"Who won the tata ipl match between Mumbai Indians and hydrabad",
    id:3,
    img:"hi.jpg",
    desc:"Yesterday there was a match between two best teams of tata ipl.Mumbai Indians vs Sunrisers Hyderabad ",
    content:`Yesterday there was a match between two best teams of tata ipl.Mumbai Indians vs Sunrisers Hyderabad.Mumbai Indian have won 5 trophy of ipl and Hyderabad had won 1 trophy of ipl so due this week can say that both the teams are best in tata ipl.The match started with the toss and toss was wonderful by Mumbai Indians and they opted to ball first after that  openers of sunrisers Hyderabad came for batting from starting onwards they started to hit boundaries in the game.Mumbai Indians gave the chance for a young for balling but this was there biggest mistake because he gave more runs in this match his name was mafaka and he is and South African player he gave 66 runs at four over.Travis head played very well in this match and he scored half century in this match.He scored 62 runs at 24 ball with 9 fours and 3 sixes.In this match mayank agrawal tried to hit some boundaries but it was not possible from him and he got out just scoring 11 runs at 13 balls.After that abhisek warma came for batting he also played very well in this match he scored 62 runs at 24 balls.He also completed his half century in this match.And after the wicket of traves head markram came for batting and he also played and after Abhishek warma got out and after this klaaseen came for batting at peach.And after he arrived at ground he just started to smashed the boundary against Mumbai Indians.Klaaseen is the wicket keeper of sunrisers Hyderabad and in last match he scored well for sunrisers Hyderabad against kkr but they were not able win that match.But in this match due to well gameplay of Hyderabad players they scored 277 runs at 3 wicket in 20 overs and this was highest score in the ipl history earlier it was the record of RCB of 263 runs at 20 overs but in today's match it got broke up.After that in second innings Mumbai Indians came for batting in starting Rohit and ishan kishan started to smashed some boundaries but after that Mumbai Indian lose their first wicket of ishan kishan.And after few overs they lost their second wicket in the form of Rohit Sharma.Munbai Indians tried very much chased the runs but they were not able to that because Hyderabad ballers played well but than also Mumbai Indians players scored 246 runs at 5 wicket.At last sunrisers Hyderabad won there first match of ipl 2024.And Mumbai Indians has lost its second match of ipl.It was the wonderful match because in this match previous records of ipl got broken.`

},
{

    title:"Who won the tata ipl match between CSK and Delhi Capitals",
    id:4,
    img:"cskvsdc.jpg",
    desc:"Who won yesterdays match held between chennai super kings vs delhi capitals ",
    content:`Who won yesterdays match held between chennai super kings vs delhi capitals it was wornderful match.In the starting delhi captitals won the match and they opt to bat first anf this match going in delhi 
    stadium before this match all the home teams matches have eon the the matches in this tata ipl 2024.In the starting of the match the openers of delhi team came on the cris,The operners where prithvi sha2 and david warner.David warner is an autralian batsman and prithvi shaw
     is the indian batsman.The first over of csk was given to deepak chhar.In the starting match delhi was in full form because their both the opener started to smash in the power play overs.Prithvi shaw scored 43 runs at 27 balls with 4 fours anf 2 sixes it was the massive batting
      prithvi shaw in this match.And david warner scored his half century in this match with the runs of 52 at 35 balls eith 5 fours and 3 sixes it was the msssive batting of david warner after the wicket of both the openers.Than delhi was facing some problems to increase the score on
       scoreboard than the captain of delhi captitals came on the cris in the form of rishab pant.Who has just recovered after his road accident.After coming on the cris he started to smashed four sixes.He scored 51 runs at 32 balls with 4 fours and 3 sixes.After that mitchell marsh also scored 18 runs at 12 balls with 2 fours and 1 six.
       After this the baller of pathirana took the wicket of them.And at last delhi captitals scored 191 at 20 overs.In the second innings of this match csk opener came for batting ruturaj gaikwad who is the captain of csk team and ravindra.In the starting over csk team got shocked because there best player got out just by making 1 runs at 2 balls in the form of ruturaj gaikwad.After that in thirs over csk lost there 3 wicket
        in the form of ravindra.After that ajinkya rahanae came on the cris and took the scoreboard at high he scored 45 runs at 30 balls with 5 fours and 2 sixes.And with him on the other side daryk mitchell was also playing well they both did the partnership  of 79 runs.But after that csk lost there wicket.And shivam dube came for batting he also scored just 18 runs at 17 balls.
        After that daryl mitchelllost his wicket and than samir vizvi came for batting and he also got out at 0 runs.After that ravindra jadeja came for batting and he scored 21 runs at 17 balls.After that dhoni came for batting on the cris all the csk fan where shouting for dhoni and it was the proud moment for every csk fan because thala was coming for batting.After arrving dhoni he smashed his bat and ball
         went for a six after that at 
        last over dhoni scored 20 runs at 6 balls.
        But he finished his game with an 6.Alrough csk lost the match but there fans where happy because they saw dhoni in batting.Dhoni scored 37 runs at 16 balls.And delhi captitals won there first match against csk in this tata ipl 2024`

},
{
    title:"Who won the tata ipl match between Gujrat titans and hydrabad",
    id:5,
    img:"gtvssrh.jpg",
    desc:"Yesterday there was a match between two best teams of tata ipl Gujrat titans vs Sunrisers Hyderabad ",
    content:`Who won the match held between gujrat titans and sunrisers hydrabad on 12th march in afternoon.In the startibg of the match gujrat won the toss and they opt to bat first.After that both the openers of gujrat titans
     came on the cris for batting.Wriddhiman saha and shubnam gill.Saha is the wicket keeper of gujrat titans.And shubnam gill is cpatain of gujrat titans team.Gujrat anf hydrabad both the team have won 1 trophy in the history of tata ipl.
     In the starting of the match gujrat titans started to smash boundaries in the powerplay overs.Both of then did the partnership of 61 runs at 41 balls.This was the massive gameplay fron both of them.But after that srh got there first wicket in the form of saha.After that sa sudarshan came on the cris for batting.Saha scored 25 runs at 13 balls with 1 four anf 2 sixes and this was nice batting of saha in this match.But he was able to scored more higher runs for his team in this match.But the captain of srh took his wicket.After that gujrat lost there second wicket in he form of shubnam gill who tmis the captain of gujrat titans he also scored well runs.He got out at abdul samad balling and catch was done by markhande.Shubnam gill scored 36 runs at 28 balls with 2 fours and 1 six.After that from gujrat side david miller came for batting and he also played very well in this match he was not out in whole match.But he does not score half century he was just 6 runs far away from his half century in this match.After the wicket of sai sudarshan vijay shankar came for batting.Sai sudarshan also played very well in this match he scored 45 runs at 36 balls with 4 fours and 1 six.He got out at the balling of abhishek sharma and catch was done by cummins.After 20 overs of batting gujrat titans scored 168 runs at 3 wicket.In the innings of sunrisers hydrabad Mayank agrawal anf travis head where the openers from the srh team.In the starting of the match srh was playing well but after that srh lost there first wicket in the form of head.Head scored 19 runs at 14 balls with 3 fours and 0 six.After that srh lost there second wicket in the form of mayank agrawal.Abhisek sharma came for batting and played well for his team.He scored 29 runs at 20 balls with 2 fours and 2 sixes.After that klaasen came for batting who is the wicket keeper of srh.And the best batsman in srh team.But in todays match he also got out very fast in the balking rasid khan.Klaasen scored just 24 runs at 13 balls with 1 four and 2 six.Shahbaaz ahmed scorwd 22 runs at 20 balls with 1 four and 1 six.Abdul samad played very well in this match he scored 29 runs at 14 balls with 3 fours and 1 six.But last they scored 162 runs with 8 wicket in 20 overs due to this gujrat titans won this match with 7 wickets.`

},

{

    title:"Who won the tata ipl match between LSG and PUNJAB Kings",
    id:6,
    img:"punjabvslsg.jpg",
    desc:"Yesterday there was a match between two best teams of tata ipl Punjab Kings vs lucknow super gaints ", 
    content:`Who won the match held between punjab kings and Lucknow super giants ?
On 11 th of March the match was held between the two legendary teams of tata ipl 2024.Kings 11 punjab captain is shikar Dhawan and Lucknow super giants captain was KL Rahul.In the first innings of the match Lucknow opt to bat first .The openers of Lsg were quniton de kock and kl Rahul.De kock is wicket keeper of Lsg.In the starting LSG started to start smash shorts in the powerplay and it was massive game play of lsg till now in ipl.After tha lsg lost there first wicket in the form of kl Rahul.Kl Rahul scored 15 runs at 9 balls and it was nice gameplay from kl Rahul.He got out in the balling of arshdeep Singh and catch was done by bairstow.After that from lsg side padikal came for batting and after few balls of batting he also got out in the match.Padikal scored just 9 runs at 6 balls with 2 fours.After markas stonnis came for batting and also got out after scoring 19 runs in 12 balls with 2 sixes.The best batting was done by Quinton de kock he scored half century in that match.With 54 runs at 38 balls with 5 fours and 2 sixes.After that pooran came for batting after the wicket of decock.Pooran scored 42 runs at 21 balls and pooran was the captain of lsg.He scored 42 runs at 21 balls with 3 sixes and 3 four.This was wonderful batting from pooran as a captain.And his strike rate was massive 200.Pooran got out in the balling of rabada with stumping bold.After aayush came for batting from lsg side and he scored just 8 runs at 10 balls with 0 boundry and this was not enough to score runs to win this match.After his wicket krunal pandya came for batting and he played very well in this match after Quinton decock.He scored 43 runs at 22 balls with 4 fours and 2 sixes this was the best batting of krunal pandya in this season till now.And he not out till whole match.After that the player at another side got out in place of him Ravi bishnoi came for batting and he got out at 0 runs in the balling of Sam Curran.After his wicket mohsin Khan came for batting he scored just 2 runs and he also got out during run out.After that Naveen ul haq came and he played 0 balls and after that 20 overs got completed.In the second innings of the match punjab going to bat.There openers came on the cries for batting.Shikar Dhawan who is the captain of punjab was opener with Jonny bairastow.They both played very well in this match.It was the massive batting of punjab in this match.Shikar Dhawan scored total 70 runs 
at 50 balls with 7 fours and 3 sixes due this type boundaries he scored 70 runs but he got out in the balling of mohsin Khan and catch was done by de kock.Bairstow on the another side he also played very well he scored 42 runs at 29 balls with 3 sixes and 3 fours.But after some time he also got out in that match in the balling mayank yadav and catch was done by stonnis.After that from punjab side prabhsimran Singh came for batting and he scored 19 runs at 7 ball with 1 four and 2 sixes.After that he also got out.And then Liam Livingstone came for batting and he scored 28 runs at 17 balls with 2 fours and 2 sixes and we was not out till last overs.Sam Curran scored just 0 runs he got out in the balling mohsin Khan.After his wicket Shashank Singh came for batting and she scored just 9 runs in 7 balls with one four.Due to this type batting of punjab in this match they were not able to win this match against lsg.Lsg won there first match against punjab in this season of tata ipl 2024.
`
},

{

    title:"Who won the tata ipl match between MI vs RR",
    id:7,
    img:"mivsrr.jpg",
    desc:"There was a match between two best teams of tata ipl MI vs RR", 
    content:`Who won the yesterday's match held between rajasthan royals and Mumbai Indians ?
Yesterday was the match held between two legendary teams of tata ipl 2024 between rajasthan royals
 and Mumbai Indians.It was the date 14 march when this match started and RR won the toss and option to ball first.The first innings 
 of the match was of Mumbai Indians.The openers of Mumbai Indians came on the cries.Rohit Sharma and inshan kishan were the openers of Mumbai
  Indians.In the starting Mumbai lost there first wicket in the form of Rohit Sharma he got out at 0 runs in the balling of Trent boult and catch
   was done by the captain of RR Sanju Samson.After that Naman dhir came for batting and he also got out at 0 runs in the balling of Trent boult.
   After that dewald brevis came for batting and he also got out at 0 runs in 1 ball in the balling of Trent boult and catch was done by nandre burger.After that tilak Verma came for batting he played very well for his team he scored 32 runs at 29 balls with 2 sixes.After that on the another side MI lost there fourth wicket in the form of Ishan kishan who is the wicket keeper of Mumbai Indians.After hardik pandya came for batting from Mumbai team and he is the current captain of Mumbai Indians.He played nicely in this match he scored 34 runs at 21 balls with 6 fours.After that he also got out in the balling of piyush chahal.After his batting piyush chawla came for batting and scored 3 runs at 6 balls with 0 boundaries and he also got out in the balling of avesh Khan.After that Tim David came for batting on stadium and he scored 17 runs at 24 balls with 1 four and he also got out in the balling nandre.After that Gerald coetze came for batting he scored 4 runs at 9 balls.At last bumrah and aksh madhwal came for batting they both scored total 12 runs in 14 balls.After 20 overs got completed.And due this type of batting of Mumbai Indians they just scored 125 runs at 20 overs.In the second innings of the match RR openers came for the batting.Yashasvi jaiswal and Jos butler both where the openers of rajsthan royals.In the starting they both played very well.But after some time RR lost there first wicket in the form of yashasvi jaiswal he scored 10  runs at  6 balls with 2 fours in the balling of kewna mafaka.After that the captain of RR came for batting who is also an wicket keeper of RR team.And he scored just 12 runs at 10 balls with 3 fours.After that riyan parag camed for batting on the cries.But on the another side Jos butler looses his wicket in the balling of akash madhwal.After that ravichandra Ashwin came for batting and he played well for a while but after 15 balls of playing he got out in the balling of akash madwal.He scored 16 runs at 16 balls with 1 four.After that shubam Dubey came for batting and he scored 8 runs at 6 balls with not out.On the another side riyan parag was smashing the shorts for his team.Due to the impact full batting of riyan parag RR won the match.He scored 54 runs at 39 balls.With 5 fours and 3 sixes this was wonderful full batting of riyan parag in this match.The man of the match was Trent boult because he took three wicket for his team in this match he is the best ballers of New Zealand.`





},



{
title:"Who won the tata ipl match between DC  and KKR",
id:8,
img:"dcvskkr.jpg",
desc:" There was a match between two best teams of tata ipl DC and KKR", 
content:`Who won that days match held between KKR vs Delhi capitals?
It was the massive gameplay from both the teams both the teams there 100% to win this match but only one 
team was able to win that match let's see the summary of match and won this match at last.In the starting Kolkata knight riders won the toss
 and they opted to bat first.The openers of the kkr team were Narine and salt.Salt is the current wicket keeper of kkr team and he plays very
  well.And he plays for the England team.And Narine is an West Indies player.In the starting of the match both the openers played very well but
   after some time salt lost his first wicket.After that from Kolkata team angkrish raghuvanshi came for batting on the cris.Than he also played very well for his team he scored 54 runs at 27 balls with 5 fours and 3 sixes with the strike rate of 200.On the another side Narine was also in full form and he also played very well in this match.He scored 85 runs at 39 balls with 7 fours and 7 sixes.After that angkrish raghuvanshi lost his wicket in the balling of nortje and catch was done by ishant.After that Russell came for batting and he also played very well he scored 41 runs at 19 balls with 4 fours and 3 sixes.Than after some time he also lost his wicket.After that the captain of KKR came for batting shreyas Iyer and he scored just 18 runs with 0 four and 2 sixes.He got out in the balling of Kaleel Ahmed.After that Rinku Singh came for batting and he played well in this match he scored 26 runs at 8 balls with 1 four and 3 sixes.After  some time he also got out and than venkatesh camed for batting and he scored just 5 runs.Than ramandeep camed for batting and he scored 2 runs and got out.After that starc came for batting and he played just 1 ball with not out.Because 20 overs got completed and due to this KKR scored 272 runs in 20 overs with 7 wicket.In the second innings Delhi capitals openers camed for batting David Warner and prithvi shaw.In the starting they played some how well.But after some time they got out.David Warner scored 18 runs at 13 balls with 2 fours and 1 six.And prithvi shaw scored 10 runs at 7 balls with 2 fours he got out in the balling and vaibhav arora.After that from Delhi side Mitchell marsh came for batting and he got out at 0 runs in the balling g of Mitchell starc.After that abhisek came for batting and he also scored 0 runs at 5 balls.After that the captain of Delhi team camed for batting Name Rishab pant And he played very well in this match.He scored 55 runs in 25 balls with 4 fours and 5 sixes.But then he got out in the balling chakravarthy.After that tristann Stubbs camed for batting and he played well and he scored half century in this match He scored 54 runs at 32 balls with 4 fours and 4 sixes.Than he also got out and after that axar Patel camed for batting and he scored 0 runs.Than sumit kumar came for batting and he scored just 7 runs.Rest of all batsman scored 1,4,1 runs and Delhi capitals got all our at 17th over and due to this type of gameplay of Delhi capitals KKR won the match easily by 106 runs.`

},
{
        title:"Who won the tata ipl match between Punjab and GT",
        id:9,
        img:"punjabvsgt.jpg",
        desc:" There was a match between two best teams of tata ipl Punjab and GT", 
content:`Who won the match held between Gujrat titans and Punjab kings ? It was the best match of tata ipl 2024.Both the teams
 gave there 100 % of efforts for winning this match and all the players of both the team played very well.Lets see which team won 
 the match by using summary.The toss was won by punjab kings and they opted to ball first.The opened of the GT where w Saha and shubnam gill
  both the players plays for Indian team.In the starting of match GT played very well Both the openers started the match very well.Saha scored 11 runs at 13 balls and he got out he scored 2 fours and he got out in the balling of rabada and catch was done by shikar Dhawan.After that from GT side Williamson came for batting and he scored 26 runs at 22 balls with 4 fours and 0 sixes.He got out in the balling g of harpreet brar.And catch was done by baristoe.After that sai Sudarshan came for batting and he played massive in this match he showed his best gameplay he scored 33 runs at 19 balls with 6 fours.And on the another side the captain of GT shubnam gill was in full form he showed why he is known as the best player of Indian team.He scored 89 runs at 48 balls with 6 fours and 4 sixes.After that Vijay Shankar came for batting after the wicket of sai Sudarshan and he scored just 8 runs at 10 balls.And than he also got out in the balling of rabada Than Rahul tewatia camed for batting from GT side and he scored 23 runs and 8 balls.Fue to the batting of GT like this they score 199 at 4 wickets.In the starting of the second the openers of punjab kings came on cris.The opener where shikar Dhawan and Jhonny bairstow.Shikar Dhawan got out in the 2 balls after the second  innings started in the balling of Umesh yadav.And after his wicket prabhsimran Singh came for batting and he played well in this match he scored 35 runs at 24 balls with 5 fours and 1 six.After this type of massive batting he got out in the balling of Noor Ahmed.And catch was done by Mohit Sharma.After that Sam curran came for batting from punjab side and he scored just 5 runs at 8 balls.He got out in the Valli g of azmatullah and catch was done by Williamson.Fhan sikandra Raza came for batting and he scored 15 runs  at 16 balls and he also got out after some time.Than Shashank Singh came for batting from punjab side and he played very well in this match he scored 61 runs in 29 balls with 6 fours and 4 sixes.Bairstow scored 22 runs at 13 balls  in this match.On the another side all the players were getting out .Jitesh Sharma came for batting and he scored 16 runs.Than ashutosh Sharma came for batting and he scored 31 runs at 17 balls and he was the impact player from punjab side and he played very well in this match.Than he also got out.After some time harpreet camed for batting and he scored 1 runs at 2 balls.Due to the such type of batting of Punjab kings they won this match with 3 wickets.`
},
{
    title:"Who won the tata ipl match between CSK and SRH",
    id:10,
    img:"cskvssrh.jpg",
    desc:" There was a match between two best teams of tata ipl CSK and SRH", 
content:`
Who won the match held between the two popular teams of tata ipl 2024.Srh vs chennai super kings match.It was the best gameplay of all the times from both the teams.Both the teams gave there 100 percent for winning this match.This match was held on 5 April 2024.In this match srh won the toss and they opt to ball first and they chance for CSK team for batting first.Csk is the team who won the ipl trophy last year.They are they are defending champion of 2023.Csk has won 5 trophy till now in the history of tata ipl.Srh have won only 1 trophy till now in the history of tata ipl.In the first innings of the match the openers of the CSK team came off the crie for batting.Both the openers where ruturaj gaikwad and Ravindra.Both are the best player of CSK.In the starting of the match both of team played very well.But there partnership was broken by bhuneshvar Kumar he made out of ravindra at 12 runs.Ravi drama scored just 12 runs at 9 balls with 2 fours.After that ajinkya rahane camed for batting from CSK side.And he played well in this match he scored 35 runs and 30 balls with 2  fours and 1 six.On the another side ruturaj was also in full form he also gave his 100% in this match to make CSK win this match.He scored 26 runs at 21 balls with 3 fours and 1 massive six.But after that ruturaj lost his wicket in the balli g of shahbaaz ahmed and catch was done by Abdul samad.After that Shivan dube 
came for batting and he also played nicely in this match he was just 5 runs far away from half century but at 45 runs he lost his wicket  in the balli g of cumming and catch was done by bhuneshwar Kumar.He scored 45 runs at 24 balls with 2 fours and 4 sixes.On the another side ajinkya rahane also lost his wicket in this match he scored 35 runs and got out in the balli g of jaydev unadkat.After his wicket ravindra jadeja came for batting.And after the wicket of Shivam dube than Mitchell camed for batting and he also lost his wicket at 13 runs with 11 balls with 1 fours and 0 sox.After his wicket the legendary player of tata ipl 2024.The best player on the planet camed for batting named ns dhoni who is the wicket keeper of CSK team and last year captain of CSK team.Due to his captainship CSK has won 5 trophy till now.But he played just 2 balls in that and scored 1 runs.Due to this type of batting of CSK in this match CSK scored  165 runs at 5 wicket in 20 overs.In the second innings of the match the srh camed for batting and there openers where in full form they where having 100% confidence that they will win this match very easily.Openers of srh where Travis head and Abhishek Sharma.Both of them played very interesting the starting of powerplay.Travis head scored 31 runs at 24 balls with 3 fours and 1 six.He got out in the balling of theekshana and catch was done by reaching ravindra.On the non strike side Abhishek scored 37 runs and 12 balls with 3 fours and 4 sixes.And he got out in the balli g of Deepak chahar.After this Aiden markram came for batting and he scored his half century in this match just at 36 balls.He got out in the balling moeen Ali.And Shahbaz Ahmed on the another side he scored 18 runs at 19 balls with 1 six.Then the best player of srh camed for batting who is the wicket keeper of srh team named Heinrich klaasen and he was not out till last over of the match innings he scored just 10 runs.On the non strike side nitish Reddy was with him and due to the such type of batting of srh team they won this match by 6 wicket at 18.1 overs.`
},
{
    title:"Who won the tata ipl match between RCB and RR",
    id:11,
    img:"rcbvsrr.jpg",
    desc:" There was a match between two best teams of tata ipl RCB and RR", 
content:`
Won the match which was held between the two best teams tata ipl 2024.Rajsthan royals vs Royal challengers banglore.Till now in the history of tata ipl RR has won one trophy of tata ipl and RCB had 0 trophies till now in the history tata ipl.Both the teams have best players of India Cricket team.Rcb had the king of the cricket named Virat Kohli and RCB has the best batsman on the planet from England name Jos butler.The toss was wonderful by RR and they opted to ball first they gave chance to RCB to bat first.In the first innings of the match the RCB openers came on the cries for the batting the openers where Virat Kohli and faf duplessis both are the best player of tata ipl .RCB players started this match with nice gameplay.Both the openers where in full form  both of them gave there 100% to score more in this match.The RCB lost there first wicket in the form of du plessis he got out in the balli g chahal and catch was done by Jos butler.He scored 44 runs at 33 balls with 2 fours and 2 sixes with strike rate of 133 in this match.After his wicket Maxwell camed for batting and he scored just 1 runs in this match and he also got out at 3 balls.He got out in the balling of nandre burger.Than after his batting saurav chauhan camed for batting from RCB side and he scored 9 runs and he also got out at 6th ball.He got out in the balling of chahal.After his batting green came for batting and he scored 5 runs at 6 balls with not out
 till last over.On the another side the king Kohli was in full form he scored the first century of tata ipl 2024.He scored 113 runs at 72 balls with 12 fours and 4 sixes.Due to the such type of batting of kings Kohli RCB scored 183 runs at 3 wicket in 20 overs.In the second innings of the RR came for batting the openers of RR team where Jos butler and yashasvi jaiswal.But in the starting of the match RR got shock after the wicket of yashasvi jaiswal at 0 runs at 2 balls He got out in the balling of topley and catch was done by Maxwell After his wicket the captain of RR came for batting named sanju Samson and he is also the wicket keeper of RR team.And he played very well in this match.He beat Massive sixes and fours.Sanju Samson scored his half century in this match He scored 69 tu s at 42 balls with 8 fours and 2 sixes in the strike rate of 164.On the another side Jos butler was also in full form he scored his 1st century of tata ipl 2024.He scored 100 runs at 58 balls.On the another side of the match Sanju lost his wicket and riyan came for batting and Riyan got out in the balling of Yash Dayal at 4 balls.After his wicket dhruv jurel came for batting and he scored 2 runs and he also got out in this match.After his wicket shimron hitmyer came for batting and he scored 11 runs with not out.At last ball Jos butler smash a massive six and he completed his century.He scored 100 runs at 58 balls with 9 fours and 4 sixes.Due to the such type of batting performance of RR they won this match easily and reach at the top points table of tata ipl 2024.
`
},
{
    title:"Dolly Brand Ambassador of windows 12",
    id:12,
    img:"dolly.jpg",
    desc:" Dolly chaiwala is the brand ambassador of windows 12 is this news is true or not ?", 
content:`
Dolly chaiwala is famous social media influencer which leaves in Nagpur.The orange city of maharastra.Dolly chaiwala is the famous tea seller in Nagpur.He his famous for his unique dress and stylish clothes.Dolly started his chai tapri in 2013.And he got famous on social due to his stylish look and tea making style.He got more famous when he meet billgates and made a video with him which gone viral on social media and he got to much famous.Journey of dolly chaiwala how he became successful.In 2019 when corona came lots of the people got quarantine.And they started to spend there whole time on social media.Then most of the people started to make vlogs on there regular works.Such that most of the youtuber and vlogger started to make food vlogging video.They started to visit roadside food maker and make there how they cook the food and how they sell the food.Like this some vlogger visit to dolly ki tapri.And they started to make video on him due to his stylish and look and unique chai making style he got famous on there video.After the video gone viral on Instagram using an hastag of stylish chaiwala.Lots of food vlogger came to visit dolly ki tapri and they started to make videos.He got more famous when the bike rider uk07 visited on his tapri.And  than he got the boost on his social media.Than lots of flimstar also came to meet him and taste his chai.Real name of dolly is Sunil Patel.He recently meet to Bill gates and made a video which gone very much viral.And due to viral video lots of people started to make rumours that the dolly chaiwala is the next brand ambassador of windows 12 but it is the fake news.Though the dolly chaiwala is an famous social media influencer but he not a tech guru and he don't know about it.The rumours are spreading by the people that he is the brand ambassador of windows 12.Many celebrity visited his chai tapri such as anurag dobhal,Nimrat Kaur,Nani,Asish vidyarti and many more.Though the billgates drink the chai made from dolly but it was the fake news that dolly will be the next brand ambassador of windows 12.Windows is the operating system which is developed by Microsoft.The latest version windows is windows 12 which is going to launch with in few days.And due this rumours started to spread that dolly is brand ambassador of windows 12.
`
},
{
    title:"Who won the tata ipl match between CSK vs KKR",
    id:13,
    img:"cskvskkr.jpg",
    desc:" There was a match between two best teams of tata ipl CSk  and KKR", 
content:`
Who won the match which was held between CSK and kkr?The tata ipl is the premier league of India.Which is organised for giving the chane for
 a new players for show there gameplay in this league.Most of the players from all over the world take part in this league.The players from England, 
 Australia,New Zealand,West Indies,South Africa and many more take part in this tournament.This league is held for two months.And it is very much famous league in India.
 All the cricket fans from all over the Indian and world watch this tournament and support there team.For this trophy many teams play matches with each other and qualify for the finals and semi finals.This is toughest league in India.The teams from all over India participate in this tournament.Teams are such as chennai super kings,Royal challengers banglore,Mumbai Indians, Kolkata knight riders, Lucknow super giants,Gujrat titans,Delhi capitals and many more this teams play matches
  and increase there point just by winning the matches the team who has more points at the points table they qualify for the finals and semifinals.The team who win the final that team may get the ipl trophy.There are two teams who have more amount of ipl trophy till now in the history of tata ipl one chennai super king and another is Mumbai Indians.Kolkata knight riders has won 2 trophies and SRH and RR had won 1 each.On 8th of April there was a match between two legendary teams tata ipl one CSK and another one kkr.CSK won the toss and they opt to ball first they gave chance to kkr for batting.In the starting of the match both the openers came to the pich.Salt and Narine was the openers of kkr.Narine is an West Indies player and salt is an England players.Salt is also an wicket keeper of kkr.In the start of the first ball kkr lost there first wicket in the form of salt.On the another side Narine scored 27 runs at 20 balls with 3 fours and 2 six.After the wicket of salt angkrish raghuvanshi came for batting and he scored 24 runs at 18 balls with 3 fours and1 six.Than he got out in the balling of jadeja.After his wicket the captain of KKR came for batting and he scored 34 runs at 32 balls with 3 fours and 0 six and than he also got out.After his wicket venkatesh Iyer camed for batting.And scored just 3 runs and got out.Ramdeep  came for batting and he scored 13 runs and he got out in 12 balls.Than after his batting Rinku Singh came for batting and he scored 9 runs.On the another side Russell came for batting and he scored just 10 runs and got out.At 20 overs of batting KKR they scored just 137 runs at 9 wicket.In the second innings of the match CSK openers started the match with nice gameplay but after sometime CSK player rachin ravindra lost his wicket.And Daryl Mitchell came on his place.And ruturaj gaikwad was in full form he played very well in this match he scored 67 runs at 58 balls with 9 fours.After the wicket of Daryl Mitchell Shivam dube came for batting and he scored 28 runs and he got out.Than the best player CSK came for batting and he scored just 1 run ms Dhoni with not out.Csk won the match 7 wickets.Man of the match was ruturaj gaikwad.
`

},
{
    title:"Who won the tata ipl match between Punjab vs RR",
    id:14,
    img:"punjabvsrr.jpg",
    desc:" There was a match between two best teams of tata ipl Punjab  and RR", 
    content:`

    Who won the match which was held between rajsthan royals and Punjab kings ? On 13 of April there was the match between two best teams of tata ipl 2024 one rajsthan royals and Punjab kings.In the history of tata ipl rajsthan royals had won tata ipl trophy and Punjab with 0 times.But both the teams have best player from all over the world such as Jos butler,shikar Dhawan,Shimron hitmyer and Sam curran Sanju Samson and Trent boult and many more.In points table rajsthan royals is at top most successful team till now in 2024 tata ipl.The first innings of the match rajsthan won the toss and they opt to ball first.The openers from punjab team where atharva taide and bairstow.In the start of the innings punjab openers played very well but after some overs atharva taide lost his first wicket in the balling avesh Khan and catch was done by kuldeep sen.He got out at 15 runs in 12 balls with 2 fours and 0 six with strike rate of 125.After his wicket prabhsimran came for batting from punjab side and he scored 10 runs at 14 balls and he also got out.On the another side bairstow also lost his wicket he scored 15 runs at 19 balls with 1 fours.He got out in the balling of maharaja and catch was done by hitmyer.Sam Curran after his wicket for batting.He is current captain of punjab kings.He scored 6 runs at 10 balls and he got out.After his wicket jitesh Sharma came for batting who is the wicket keeper of punjab kings.He scored 29 runs at 24 balls with 1 four and 2 sixes.After 29 runs he lost his wicket in the balling of avesh Khan.Shashank Singh came for batting after his wicket.He scored 9 runs and lost the wicket.After his batting Livingstone came for batting on the cries.He scored 21 runs at 14 balls with 2 fours and 1 six.After 21 Livingstone lost his wicket in runout.Ashutosh Sharma scored 31 runs at 16 balls and than he lost his wicket.After this harpreet came and he scored 3 runs at 3 ball with not out in the end of 20th over.Punjab scored 147 runs at 7 wicket in the 20 overs of playing.Avesh Khan took 2 wicket and maharaja also took 2 wicket in this match.Chahal,boult ,kuldeep sen took 1 wicket each.
    In the second innings of the match rajsthan royals camed for batting.Both the openers where yashasvi jaiswal and tanush kotian.They started very well Both of them scored 63 runs in the 8 over but after some time they lost there wicket yashaswi jaiswal scored 39 runs at 28 ball with 4 fours and lost his wicket in the balling of rabada.Tanush lost his wicket in the balling of Livingstone he scored 24 runs at 31 balls with 3 fours and 0 six.After there batting Sanju Samson came for batting from punjab side.Sanju is the current captain of punjab kings and also the wicket keeper of punjab.He scored 18 runs at 14 balls and lost his wicket.After his batting riyan parag came for batting and he scored just 23 runs and lost his wicket.After his batting the dhruv jurel came for batting on the pich and he scored 6 runs.Than shimron hitmyer came for batting and he played very well in this match he scored 27 runs at 10 balls on the another side all the players where loosing there wicket such rovman powell keshav maharaja .This type of batting of Rajasthan player they won the match very much easily.They scored 152 runs at 7 wicket with 19.5 overs.Rajsthan won this match very match easily.
    `

},
{
    title:"Why tata ipl is famous",
    id:15,
    img:"ipl.jpg",
    desc:"Why ipl is famaous", 
    content:`
  

Why ipl is famous social much ? Tata ipl is the very popular tournament in the history of Indian cricket.It is most loved tournament in the India.The people from all across the India watch this tournament there are major 8 teams which plays the ipl with each other.The team who wins the final of ipl they get the trophy of tata ipl 2024.There are many teams play in this tournament such Royal challengers banglore,Rajsthan royals,Chennal super kings,Gujrat titans,Lucknow super giants,Kolkata knights riders,Delhi capitals,Mumbai indians.This are the major teams of tata ipl which plays the match with each team and the team which wins they get points upon there score and wickets.The players across all world come to play this tournament in India.Player come from different countries such as Australia,New Zealand,England ,West Indies,South Africa,Srilanka and many more.They play with each other to win this tournament.They get divided into each team and they play.According to the ipl auction rule.Each team must have only 5 foreigners in there team.Rest of the players they may have to keep from our own countries.Due to the this type of rule the new players get chance two show up there skills in this tournament.Such as mafaka from South Africa he plays in Mumbai Indians and he is first arm baller.Rinku Singh he got selected in Indian team due to the ipl.In last season of ipl Rinku hit 5  sixes in one match and made kkr to win the match.And due to this type of gameplay of Rinku Singh he got selected in Indian team.There are many new players which have get selected in Indian team with the help of ipl.Such has bhuneshvar Kumar,Hardik pandya,K k Rahul ,Krunal pandya,Shubnam gill,Deepak chahar,Uvi chahal and many more.They started there carrier from ipl but now they are best players of Indian cricket team.Three teams are most popular in this ipl tournaments such as Chennai super kings this team is famous due to the Mahindra Singh Dhoni,Royal challengers banglore this team is famous due to the Virat Kohli,Mumbai Indians this  team is famous due to Rohit Sharma.Most successful teams of tata ipl are Chennai super kings and Mumbai Indians.Chennai has won 5 trophy under the captainship of Mahindra Singh Dhoni.Mumbai Indians had also won 5 trophy under the captainship of Rohit Sharma.

    `

}
]